### PR TITLE
first file

### PR DESCRIPTION
**Pull request by RickyCode**
creation of the hello world function

### CODE REVIEW

**Comment by arielarmijo** [comment]
Me parece muy bien!

**Review by RickyCode — COMMENTED** [review]
you forgot leave a blanck line at the end

**Review by carrizotamara — APPROVED** [review]

**Review by arielarmijo — APPROVED** [review]

**Review by d-jv — APPROVED** [review]

**Review by lanavia — APPROVED** [review]
let's go!

**Review by Intropac — APPROVED** [review]

**Review by Intropac — COMMENTED** [review]
All ok!

**Pull request merged**
